### ISSUE TITLE
[OTHER] Automatically run program when tapped Gitpod button

### ISSUE THREAD

**Issue by KendallDoesCoding** [Pradumnasaraf/Twitter_Bot#10]
### What would you like to share?

 Automatically run program when tapped Gitpod button

**Comment by Pradumnasaraf** [comment]
Hey @KendallDoesCoding thanks for opening issue, but due to API keys program can't be run auto.

**Comment by KendallDoesCoding** [comment]
> Hey @KendallDoesCoding thanks for opening issue, but due to API keys program can't be run auto.

Ok cool!
